name: CI/CD with terraform

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  AWS_SSH_PKEY: ${{ secrets.AWS_SSH_PKEY }}
  AWS_TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    outputs: 
      instance_public_ip: ${{ steps.get_ip.outputs.EC2_PUBLIC_IP }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Init
        id: init
        run: terraform init -backend-config="bucket=$AWS_TF_STATE_BUCKET_NAME" -backend-config="region=$AWS_REGION" 
        working-directory: ./Terraform
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var="region=$AWS_REGION" \
            -var="public_key=$AWS_SSH_PKEY" \
            -var="private_key=$AWS_SSH_KEY" \
            -var="key_name=deployer_key" \
            -out=PLAN
        working-directory: ./Terraform
      - name: terraform apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./Terraform
      - name: Read EC2 Public IP
        id: get_ip
        run: |
          echo "EC2_PUBLIC_IP=$(terraform output -raw instance_public_ip)" >> "$GITHUB_OUTPUT"
        working-directory: ./Terraform
  deploy-app:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set IP env Variable
        run: echo "INSTANCE_PUBLIC_IP=${{needs.deploy-infra.outputs.instance_public_ip}}" >> $GITHUB_ENV
      - name: Login TO ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push Docker Image
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REPOSITORY: node.app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        working-directory: ./aws-terraform-github-actions-cicd
      - name: Deploy Docker Image To EC2
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REPOSITORY: node.app
          IMAGE_TAG: ${{ github.sha }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.INSTANCE_PUBLIC_IP }}
          username: ubuntu
          key: ${{ env.AWS_SSH_KEY }}
          envs: REGISTRY,REPOSITORY,IMAGE_TAG,AWS_DEFAULT_REGION
          script: |-
            sudo apt update
            sudo apt install docker.io -y
            sudo apt install awscli -y
            aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | sudo docker login --username AWS --password-stdin "$REGISTRY"
            sudo docker stop myappcontainer || true
            sudo docker rm myappcontainer || true
            sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
            sudo docker run -d --name myappcontainer -p 80:8080 $REGISTRY/$REPOSITORY:$IMAGE_TAG